package editor

var helpLines = []string{
	"Navigation:",
	"  Tab / Shift-Tab : Focus next/prev panel",
	"  j / k           : Move selection down/up",
	"  Down / Up       : Move selection down/up",
	"  g               : Seek playback to selected line",
	"  f / Ctrl-F      : Snap selection to active playing line",
	"",
	"Playback:",
	"  Space           : Play / Pause outside text edit",
	"  Left / Right    : Seek backward/forward 1s outside text edit",
	"",
	"Editing Lyrics:",
	"  e               : Edit current line text",
	"  i               : Insert blank line before",
	"  a / o / Enter   : Insert blank line after",
	"  d               : Delete current line",
	"  s               : Split at playhead (Normal)",
	"                    Split at cursor (Edit)",
	"  m               : Merge current line with next",
	"  J / K           : Swap text with next/prev line",
	"",
	"Sync & Nudge Time:",
	"  t               : Tap-sync line to playhead",
	"  [ / ]           : Nudge Start time ±100ms",
	"  { / }           : Nudge End time ±100ms",
	"  Ctrl-[ / Ctrl-] : Fine nudge Start time ±10ms",
	"  Ctrl-, / Ctrl-. : Fine nudge End time ±10ms",
	"",
	"Commands & File:",
	"  Ctrl-S          : Save project draft",
	"  Ctrl-P          : Open project picker",
	"  Ctrl-E          : Edit project metadata (name / artist / album)",
	"  I               : Import lyrics from file",
	"  p               : Publish lyrics to server",
	"  h / ?           : Toggle help menu",
	"  q               : Quit application",
}
